.gitattributes
Diffs for minified files are pretty useless and don't communicate anything, we should make git aware of this at the repo level.
=> Treat minified files as binary

src/css/int/chn/black-highlighter_ch.css
Sekai notified me that, per an update to the -CN sidebar, an exception that was previously made for it is no longer required and is now causing issues:
=> Remove exception for -CN series sidebar links

src/css/elements.css
Currently, elements.css uses `.blockquote` to define the rules for the "blockquote" class. However, Sigma-9 defines this class with `div.blockquote`, which is a higher selector. This causes the Sigma-9 rules for the class to override the Black Highlighter rules, such as color and margin. By matching the selectors, the BHL CSS will continue to display.
=> div.blockquote

src/css/main.css
Currently, the buttons to select a version in the edit history are forced into a vertical stack, which makes it significantly more difficult to find the correct version and compare pages that use Black Highlighter. This is from the following line in `structure.css`:
```css
table:not(.form) td>input {
width: 100%;
}
```
I have found a selector that specifically affects the edit history buttons, and puts the two buttons side-by-side, as they should be, by removing the `width: 100%` argument that caused the issue.
=> Fix Edit History Stack

src/css/normalize.css
I pushed an update to the selectors used to affect the burger menu on the mobile version of Sigma-9 earlier today. This causes the segments of normalize.css that affected the burger menu to no longer apply. This change matches the selectors between normalize.css and Sigma-9 and should undo the fix. BHL uses different selectors than Sigma-9 for this element, and no further change is needed other than to normalize.css.
=> Update normalize.css to match Sigma-9

src/css/elements.css
The current width size for .hovertip elements is too narrow, and often causes long footnotes to overflow off the page length. 
[An example of this happening on SCP-3812.](https://cdn.discordapp.com/attachments/719921904991076462/799420816416702464/unknown.png) (Note that this specific footnote does barely fit on the screen in question, but it not easily readable or easy to make it display.)
Increasing the width of the hovertips to 25% will help alleviate this issue and allow longer footnotes to be read on desktop.
=> Increase Hovertip Width

Makefile, README.md, build/css.mk, build/files.mk, build/images.mk, build/int-cn.mk, build/int-template.mk, build/int-test.mk, build/int.mk, build/legacy.mk, build/meta.mk
This PR splits out Makefiles into separate files based on task type. It additionally explicitly lays out rules for INT variants, as the dynamic approach did not allow make to infer prerequisites.
=> Split out Makefiles

build/css-merge/postcss.config.js
Fixes #72 
This adds prefixes during the merge step, to ensure the full version has them in addition to the minified version. The minified version retains the prefix setting so they are not lost in that step.
=> Add prefixer to merge step

src/scp-test-page.js
This adds the option of a fallback, so if `site=xxx` is not a language code (e.g. `ko`, `en`), then it interprets it as the wikidot slug (e.g. `scp-sandbox-3`, `topia`). This allows using the tool on any wikidot page.
It also changes how URL parameter parsing works to avoid multiple passes.
=> Allow using the test page on any wiki

build/files.mk, build/install.sh, build/int-patch-and-merge.sh, build/legacy.mk, build/scp-test.mk
Darwin `install` does not support the `-D` flag, so this script does `mkdir -p` instead.
=> Use universal install wrapper for all platforms

build/install.sh, build/scp-test.mk, build/sed.sh
Similar to #86, this PR adds a wrapper for inline sed which works on Mac, which does not support normal GNU `sed -i` invocation.
=> Use universal sed wrapper for all platforms

Makefile, build/images.mk
This adds new rules to copy images statically without running the optimizer on them, since they are not going to be exported to dist. (Here they are still copied to expose them, but they are used directly in the CSS as data URIs so optimizing file outputs doesn't make sense).
=> Don't optimize images in icon directories

src/css/header.css, src/css/normalize.css, src/css/root.css, src/css/sidebar.css
This PR will add new interwiki styling to BHL. I intend for the new interwiki to be styled for BHL by importing first the normaliser and then BHL itself, just like how everything else is styled on Sigma-9 based sites. This should result in minimal changes being needed - just a few more selectors added here and there.
The new interwiki as of scpwiki/interwiki#3 has the following structure:
```css
html#interwiki
div.side-block
div.heading          (once)
p
div.menu-item[name]  (repeats)
img.image a
```
To target elements in the new interwiki, selectors like `#interwiki div.menu-item` should be applied. This looks similar to `#side-bar div.menu-item`, which could give the impression that `#side-bar` and `#interwiki` refer to similar elements (but they don't).
There's a bunch of CSS in BHL …
=> Add styling for new Interwiki

src/css/elements.css
Remove border around .rate-points due to normalize.css setting to inherit.
=> remove border from .rate-point

build/css.mk, build/postcss.config.js, package.json, src/css/black-highlighter.css, src/css/root.css
In order to speed up loading of the theme css file, the fonts.css file which includes all the `@font-face` rules is set to also be imported into the main CSS files.
In order to do so, the relative src links needed to be replaced via PostCSS and a global `sed` command on the css.mk file.
=> Adding fonts.css to the import

src/css/parts/wikidot-structure.css
Text is not centered for the save .owindow
=> center-align text in the save modal

src/css/parts/header.css
#header h1 a, h2 span does not repect mobile header height.
=> correct mobile left margin for h1,h2

.github/workflows/deploy.yaml, build/files.mk
This is the second use of `cdn.scpwiki.com` to serve theme content, see https://github.com/scpwiki/sigma/pull/81. This will be a nice, permanent solution to GitHub being blocked in various places, thus preventing people from being able to load theme data. The idea with these changes is that this CDN will be our new place for BHL asset hosting, though we will continue to push to GitHub pages as there may be unseen consumers relying on it.
The location for files will be under `/theme/en/black-highlighter/`, for instance:
* https://cdn.scpwiki.com/theme/en/black-highlighter/css/black-highlighter.css
* https://cdn.scpwiki.com/theme/en/black-highlighter/css/black-highlighter.min.css
* https://cdn.scpwiki.com/theme/en/black-highlighter/fonts/int/japanese/m-plus-1p-v19-japanese-500.ttf
=> Set up Black Higlighter to deploy to cdn.scpwiki.com

.github/workflows/deploy.yaml
(See https://github.com/scpwiki/sigma/pull/86, description copied from there)
One known issue with `cdn.scpwiki.com` has been the incorrect application of charsets onto uploaded files, causing any non-ASCII characters to render incorrectly.
This is tracked in https://github.com/aws/aws-cli/issues/1346. It seems clear that Amazon is not going to release a fix, so I have created https://github.com/emmiegit/s3-sync-action. This new action is a script which uploads each file separately, allowing us to detect and specify the MIME explicitly. This should fix the encoding issue and allow us to prepare to use the CDN for real.
I tested this using the dummy `scp-wiki-cdn-test` bucket, and confirmed that the expected file layout was present.
=> Fix text encoding issue for CDN

src/css/parts/elements.css
`display: flow-root` has browser support at over 96% according to caniuse, so the @supports can be removed, IMO. Alternatively, add display: block before display: flow-root to do the same thing slightly more compactly.
=> Remove flow-root supports

src/css/parts/elements.css
Since the `scale: 2 1` has removed by SYwaves in #215 , we should remove the corresponding `@supports not (scale: 2 1)`.
=> Remove a deprecated "supports"

src/css/parts/elements.css, src/css/parts/root.css, src/css/parts/wikidot-structure.css
Namepacing the `@keyframes` to prevent conflict/name collision, as seen in https://github.com/Nu-SCPTheme/Black-Highlighter/issues/234#issuecomment-1866062346
On a separate note, which element uses `@keyframes slide-down`? Couldn't find it to mirror the change.
=> Namespacing all @keyframes with bhl-

src/css/parts/wikidot-structure.css
Fix an issue where `grid-template-columns` in mobile queries are not adjusted, resulting in uneven whitespace on the sides of `#main-content`
=> fix margin on mobile #content-wrap

src/css/parts/wikidot-structure.css
Change `#footer .options` to display: flex and allow it to wrap on narrower screen size.
Currently, this can overflow if total width is bigger than available screen width.
Simulated with larger base font size: http://scptestwiki.wikidot.com/sytest3
=> adjust #footer .options to use flex

.github/workflows/deploy.yaml
I have already copied the secrets into this repo. This modifies the workflow to upload to our new CDN endpoint, hosted by DigitalOcean.
=> Implement new CDN workflow for Black Highlighter

.github/workflows/build.yaml, .github/workflows/deploy.yaml
I completely forgot BHL uses a different system (e.g. bun) for its build process. No wonder it wasn't deploying!
Also, to avoid the special if-logic only BHL has, I introduce a separate workflow just for checking the build.
=> Fix CDN workflow build
